### ISSUE TITLE
3 server why not 2 ?

### ISSUE THREAD

**Issue by lanaiscool** [scatterp/peatio#10]
The multiserver documentation states 3 servers a mysql server a webserver and bitcoind/rabbit-mq server cant it just be 
a mysql/webserver and a bitcoind/rabbitmq server?

**Comment by scatterp** [comment]
yes

**Comment by scatterp** [comment]
any other questions forthis do you need to know how ?

**Comment by lanaiscool** [comment]
No thanks for answering and clearing things up and thanks for the good work !
