### ISSUE TITLE
Can you please help me install a full-environment on aws?

### ISSUE THREAD

**Issue by fredxyt** [scatterp/peatio#15]
Hi @scatterp,
I'd like to pay for the install and configuration, please contact me tks.
Fred

**Comment by legends420** [comment]
i can do full install join my discord https://discord.gg/fNqTj2F

**Comment by scatterp** [comment]
sorry for the delayed reply i do not recommend using aws you can sign up with an account at contabo.com 
9 euros 12gb ram 300gb ssd if you need my help please leave your contact details here

**Comment by fredxyt** [comment]
Please contact me at fredxyt@gmail.com

**Comment by scatterp** [comment]
done

**Comment by scatterp** [comment]
contacted
