### ISSUE TITLE
trying to withdraw coins but they will not leave

### ISSUE THREAD

**Issue by lanaiscool** [scatterp/peatio#18]
i tried to withdraw coins a few times when calling to the rpc server it says balance is still on the server here i my peatio withdrawal output

it gives two fatals first 1:
I, [2017-11-15T11:02:33.447917 #2094]  INFO -- : Received: {"id":9,"locale":"en"}
F, [2017-11-15T11:02:39.094403 #2094] FATAL -- : {"code"=>-1, "message"=>"settxfee <amount>\n<amount> is a real and is rounded to the nearest 0.01"} (CoinRPC::JSONRPCError)
second 1:
F, [2017-11-15T11:02:39.094579 #2094] FATAL -- : /home/deploy/peatio/current/app/services/coin_rpc.rb:34:in `handle'
/home/deploy/peatio/current/app/services/coin_rpc.rb:23:in `method_missing'
/home/deploy/peatio/current/app/models/worker/withdraw_coin.rb:29:in `block in process'

`I, [2017-11-15T11:02:33.447917 #2094]  INFO -- : Received: {"id":9,"locale":"en"}
F, [2017-11-15T11:02:39.094403 #2094] FATAL -- : {"code"=>-1, "message"=>"settxfee <amount>\n<amount> is a real and is rounded to the nearest 0.01"} (CoinRPC::JSONRPCError)
/home/deploy/peatio/current/app/services/coin_rpc.rb:34:in `handle'
/home/deploy/peatio/current/app/services/coin_rpc.rb:23:in `method_missing'
/home/deploy/peatio/current/app/models/worker/withdraw_coin.rb:29:in `block in process'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `block in transaction'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `within_new_transaction'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `transaction'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/transactions.rb:209:in `transaction'
/home/deploy/peatio/current/app/models/worker/withdraw_coin.rb:18:in `process'
/home/deploy/peatio/current/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
F, [2017-11-15T11:02:39.094579 #2094] FATAL -- : /home/deploy/peatio/current/app/services/coin_rpc.rb:34:in `handle'
/home/deploy/peatio/current/app/services/coin_rpc.rb:23:in `method_missing'
/home/deploy/peatio/current/app/models/worker/withdraw_coin.rb:29:in `block in process'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `block in transaction'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `within_new_transaction'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `transaction'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/transactions.rb:209:in `transaction'
/home/deploy/peatio/current/app/models/worker/withdraw_coin.rb:18:in `process'
/home/deploy/peatio/current/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
`

**Comment by scatterp** [comment]
looks like a json error some how will look in to this

**Comment by scatterp** [comment]
please test with a btc withdrawal let me know if you get the same error also please create a pull request with your latest code so i can see what you have changed.. additionally if you do get an error with the btc please try with gemfile and gemfile.lock file from http://github.com/peatio/peatio repository and report results..

**Comment by SandipBhowmick** [comment]
Please review my configurations. If any change or any update require suggest me. 
https://gist.github.com/SandipBhowmick/90d5b04f4afb7f33802b79a0ced87f65

**Comment by scatterp** [comment]
please test with a btc withdrawal let me know if you get the same error also please create a pull request with your latest code so i can see what you have changed.. additionally if you do get an error with the btc please try with gemfile and gemfile.lock file from http://github.com/peatio/peatio repository and report results..

**Comment by scatterp** [comment]
@lanaiscool i fixed your error i think please create the pull request and i will commit.

**Comment by lanaiscool** [comment]
@scatterp btc withdraw works  wit no problem i.am.developing on linux not windows ubuntu server 16.04 to be precies the withdraw problem was with a coin i added

**Comment by scatterp** [comment]
yes but you are editing the files on windows

**Comment by scatterp** [comment]
if you give me your skype or something i will contact you and we can fix this issue

**Comment by lanaiscool** [comment]
This is only a issue for a particular coin please close

**Comment by SandipBhowmick** [comment]
@scatterp no btc withdrawal is working fine. Thank you for your help.
