### ISSUE TITLE
How to make an account as admin

### ISSUE THREAD

**Issue by chuakwee** [scatterp/peatio#22]
Hi, thank you for your files. I was able to setup the server and able to create one account to login to the exchange. How can i make this account as admin as i like to take a look of the admin pages? What fields in the tables that i shall change in mysql?

Thanks.

**Comment by scatterp** [comment]
none 
sudo nano ~/peatio/current/config/application.yml
you will find the email at the top 
after this you want to do 
sudo service nginx stop
bundle exec rake daemons:stop
sudo service nginx start
bundle exec rake daemons:start
bundle exec rake daemons:status

assuming everything is running you should have what you need
feel free to add me for faster support
simon.m.day (skype)

**Comment by scatterp** [comment]
also let me know if this is solved so i can close the ticket

**Comment by chuakwee** [comment]
Hi @scatterp , thanks for your help to troubleshoot, added the account in config/application.yml as admin will do. I will close this issue.
