### ISSUE TITLE
Couldn't create database and Couldn't create database ?

### ISSUE THREAD

**Issue by senisende** [scatterp/peatio#23]
I have a problem like this. I need help!

`root@DESKTOP-1HILGOC:~/peatio/current# bundle exec rake db:setup
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "database"=>"peatio_production", "username"=>"root", "password"=>nil, "pool"=>10, "reconnect"=>true}, {:charset=>"utf8", :collation=>"utf8_unicode_ci"}
(If you set the charset manually, make sure you have a matching collation)
-- create_table("account_versions", {:force=>true})
rake aborted!
Mysql2::Error: c through socket '/var/run/mysqld/mysqld.sock' (2)
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `initialize'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:440:in `new_connection'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:450:in `checkout_new_connection'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:421:in `acquire_connection'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:356:in `block in checkout'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:355:in `checkout'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:546:in `retrieve_connection'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_handling.rb:79:in `retrieve_connection'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/connection_handling.rb:53:in `connection'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/migration.rb:615:in `connection'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/migration.rb:628:in `block in method_missing'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/migration.rb:601:in `block in say_with_time'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/migration.rb:601:in `say_with_time'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/migration.rb:621:in `method_missing'
/root/peatio/current/db/schema.rb:16:in `block in <top (required)>'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/schema.rb:42:in `instance_eval'/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/schema.rb:42:in `define'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/schema.rb:62:in `define'
/root/peatio/current/db/schema.rb:14:in `<top (required)>'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load'/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `block in load'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load'/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/railties/databases.rake:254:in `block (3 levels) in <top (required)>'
/root/peatio/current/vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.12/lib/active_record/railties/databases.rake:261:in `block (3 levels) in <top (required)>'
/root/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
/root/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)`

**Comment by scatterp** [comment]
"password"=>nil
it looks like you didnt set the mysql password during setup

**Comment by scatterp** [comment]
do you have skype ?

**Comment by senisende** [comment]
I fixed "password"=>nil problem, but other same. Yes, i have Skype: muef90

**Comment by senisende** [comment]
i fixed my problem. Thanks for your good work
