### ISSUE TITLE
bundle install error on mac

### ISSUE THREAD

**Issue by crazyrunsnail** [scatterp/peatio#24]
Hi,
When I deploy on mac , I get an error when run `bundle install` and the error said:
`Could not find mina-slack-0.1.0 in any of the sources`
Can anybody help me?

**Comment by scatterp** [comment]
i can help with this but seriously why  install on a mac ? 
i mean this will be an exchange holding money either yours or someone elses 
just spend 9 euros on a server from contabo.com 
anyway for your error you dont run bundle install you have to run the command exactly as it appears in install1.sh 
if this fails use the Gemfile and Gemfile.lock from github.com/peatio/peatio
let me know how it goes

**Comment by crazyrunsnail** [comment]
@scatterp thank you,  I just meant I development in my mac and deploy in a ubuntu server.
There are something  unexpected I find in prod environment. 
When I want to add a bank in funds url , I get a error of 422 status where may meant CSRF token is not verified. Is there some configuration I didn't  config?
I'm newer to this rails and this project, thank you for your time.
