### ISSUE TITLE
Euro Depoist not working

### ISSUE THREAD

**Issue by yatindrarao** [scatterp/peatio#9]
When I deposit Euro. I get this error. 
`Started POST "/deposits/banks" for 192.168.1.41 at 2017-11-01 14:48:43 +0530
Processing by Private::Deposits::BanksController#create as HTML
  Parameters: {"deposit"=>{"account_id"=>9, "member_id"=>2, "currency"=>"eur", "amount"=>5000, "fund_source"=>2}, "bank"=>{"deposit"=>{"account_id"=>9, "member_id"=>2, "currency"=>"eur", "amount"=>5000, "fund_source"=>2}}}
  Member Load (0.2ms)  SELECT `members`.* FROM `members` WHERE `members`.`disabled` = 0 AND `members`.`id` = 2 ORDER BY `members`.`id` ASC LIMIT 1
   (0.3ms)  SELECT SUM(`trades`.`volume`) AS sum_id FROM `trades` WHERE `trades`.`currency` = 8 AND (created_at > '2017-10-31 14:48:45')
   (0.3ms)  SELECT SUM(`trades`.`volume`) AS sum_id FROM `trades` WHERE `trades`.`currency` = 9 AND (created_at > '2017-10-31 14:48:46')
  Account Load (1.3ms)  SELECT `accounts`.* FROM `accounts` WHERE `accounts`.`member_id` = 2
  IdDocument Load (18.9ms)  SELECT `id_documents`.* FROM `id_documents` WHERE `id_documents`.`member_id` = 2 LIMIT 1
#<Member id: 2, sn: "PEATZUJKUCVTIO", display_name: nil, email: "foo@peatio.dev", identity_id: nil, created_at: "2017-10-30 10:30:22", updated_at: "2017-10-30 11:04:17", state: nil, activated: true, country_code: nil, phone_number: nil, disabled: false, api_disabled: false, nickname: nil>
#<DepositChannel:0x00000006e11d28 @attributes={:id=>400, :key=>"bank", :currency=>"eur", :sort_order=>2, :bank_accounts=>[{"bank"=>"Your Bank Name", "branch"=>"Your Bank Branch", "holder"=>"Your Account Holder", "account"=>"Your Account Number"}]}>
  Account Load (0.8ms)  SELECT `accounts`.* FROM `accounts` WHERE `accounts`.`member_id` = 2 AND `accounts`.`currency` = 1 ORDER BY `accounts`.`id` ASC LIMIT 1
Completed 500 Internal Server Error in 3423ms

ActiveRecord::UnknownAttributeError (unknown attribute: fund_source):
  app/controllers/concerns/deposits/ctrl_bankable.rb:10:in `create'
  lib/middleware/security.rb:11:in `call'
  lib/middleware/i18n_js.rb:9:in `call'

  Rendered /home/br/.rvm/gems/ruby-2.2.1@rails4012/gems/actionpack-4.0.12/lib/action_dispatch/middleware/templates/rescues/_source.erb (32.0ms)
  Rendered /home/br/.rvm/gems/ruby-2.2.1@rails4012/gems/actionpack-4.0.12/lib/action_dispatch/middleware/templates/rescues/_trace.erb (36.0ms)
  Rendered /home/br/.rvm/gems/ruby-2.2.1@rails4012/gems/actionpack-4.0.12/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (35.5ms)
  Rendered /home/br/.rvm/gems/ruby-2.2.1@rails4012/gems/actionpack-4.0.12/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (280.0ms)`

![eur_deposit_issue](https://user-images.githubusercontent.com/7347855/32268184-02704e6e-bf14-11e7-861f-2c22f1185849.png)

**Comment by scatterp** [comment]
as i mentioned in the chat i am not planing to use this funds page all this will be and SHOULD BE handled by an external provider (paysafe) as an example

**Comment by scatterp** [comment]
if theres no more issue here please close the ticket or if you have further questions about this let me know

**Comment by yatindrarao** [comment]
Thanks @scatterp
